#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use Innmind\Framework\{
    Main\Cli,
    Application,
};
use Innmind\DependencyGraph\Kernel;
use Innmind\OperatingSystem\Config;

$config = Config::new()->mapHttpTransport(
    static fn($transport) => $transport->map(
        static fn($config) => $config->limitConcurrencyTo(20),
    ),
);

new class($config) extends Cli {
    #[\Override]
    protected function configure(Application $app): Application
    {
        return $app->map(new Kernel);
    }
};
