<?php
declare(strict_types = 1);

namespace Tests\Innmind\DependencyGraph\Loader;

use Innmind\DependencyGraph\{
    Loader\VendorDependencies,
    Loader\Vendor,
    Loader\Package,
    Vendor\Name,
    Package as Model,
};
use Innmind\HttpTransport\Curl;
use Innmind\TimeContinuum\Earth\Clock;
use Innmind\Immutable\Set;
use PHPUnit\Framework\TestCase;

class VendorDependenciesTest extends TestCase
{
    public function testInvokation()
    {
        $http = Curl::of(new Clock);
        $package = new Package($http);
        $load = new VendorDependencies(
            new Vendor($http, $package),
            $package,
        );

        $vendor = $load(Name::of('innmind'));

        $this->assertInstanceOf(Set::class, $vendor);
        $this->assertSame(
            [
                'aws/aws-crt-php',
                'aws/aws-sdk-php',
                'brick/math',
                'composer/pcre',
                'composer/semver',
                'composer/xdebug-handler',
                'doctrine/annotations',
                'doctrine/cache',
                'doctrine/collections',
                'doctrine/common',
                'doctrine/dbal',
                'doctrine/deprecations',
                'doctrine/event-manager',
                'doctrine/inflector',
                'doctrine/instantiator',
                'doctrine/lexer',
                'doctrine/orm',
                'doctrine/persistence',
                'formal/access-layer',
                'friendsofphp/php-cs-fixer',
                'guzzlehttp/guzzle',
                'guzzlehttp/promises',
                'guzzlehttp/psr7',
                'innmind/acl',
                'innmind/amqp',
                'innmind/ark',
                'innmind/black-box',
                'innmind/cli',
                'innmind/cli-framework',
                'innmind/coding-standard',
                'innmind/colour',
                'innmind/command-bus',
                'innmind/crawler',
                'innmind/crawler-app',
                'innmind/cron',
                'innmind/debug',
                'innmind/dependency-graph',
                'innmind/di',
                'innmind/doctrine',
                'innmind/event-bus',
                'innmind/file-watch',
                'innmind/filesystem',
                'innmind/framework',
                'innmind/genome',
                'innmind/git',
                'innmind/git-release',
                'innmind/graphviz',
                'innmind/hash',
                'innmind/homeostasis',
                'innmind/html',
                'innmind/http',
                'innmind/http-authentication',
                'innmind/http-framework',
                'innmind/http-server',
                'innmind/http-session',
                'innmind/http-transport',
                'innmind/immutable',
                'innmind/infrastructure',
                'innmind/infrastructure-amqp',
                'innmind/infrastructure-neo4j',
                'innmind/infrastructure-nginx',
                'innmind/installation-monitor',
                'innmind/ip',
                'innmind/ipc',
                'innmind/json',
                'innmind/kalmiya',
                'innmind/lab-station',
                'innmind/library',
                'innmind/log-reader',
                'innmind/logger',
                'innmind/math',
                'innmind/media-type',
                'innmind/neo4j-dbal',
                'innmind/neo4j-onm',
                'innmind/object-graph',
                'innmind/operating-system',
                'innmind/process-manager',
                'innmind/profiler',
                'innmind/rabbitmq-management',
                'innmind/reflection',
                'innmind/rest-client',
                'innmind/rest-server',
                'innmind/robots-txt',
                'innmind/router',
                'innmind/s3',
                'innmind/scaleway-sdk',
                'innmind/server-control',
                'innmind/server-status',
                'innmind/signals',
                'innmind/silent-cartographer',
                'innmind/socket',
                'innmind/specification',
                'innmind/ssh-key-provider',
                'innmind/stack',
                'innmind/stack-trace',
                'innmind/stream',
                'innmind/templating',
                'innmind/time-continuum',
                'innmind/time-warp',
                'innmind/tower',
                'innmind/url',
                'innmind/url-resolver',
                'innmind/url-template',
                'innmind/virtual-machine',
                'innmind/warden',
                'innmind/xml',
                'jeremykendall/php-domain-parser',
                'lcobucci/clock',
                'lcobucci/jwt',
                'league/uri-components',
                'league/uri-interfaces',
                'league/uri-parser',
                'masterminds/html5',
                'monolog/monolog',
                'mtdowling/jmespath.php',
                'music-companion/apple-music',
                'myclabs/deep-copy',
                'nikic/php-parser',
                'ovh/ovh',
                'phar-io/manifest',
                'phar-io/version',
                'phpunit/php-code-coverage',
                'phpunit/php-file-iterator',
                'phpunit/php-invoker',
                'phpunit/php-text-template',
                'phpunit/php-timer',
                'phpunit/phpunit',
                'psr/cache',
                'psr/clock',
                'psr/container',
                'psr/event-dispatcher',
                'psr/http-client',
                'psr/http-factory',
                'psr/http-message',
                'psr/log',
                'ralouphie/getallheaders',
                'ramsey/collection',
                'ramsey/uuid',
                'sebastian/cli-parser',
                'sebastian/code-unit',
                'sebastian/code-unit-reverse-lookup',
                'sebastian/comparator',
                'sebastian/complexity',
                'sebastian/diff',
                'sebastian/environment',
                'sebastian/exporter',
                'sebastian/global-state',
                'sebastian/lines-of-code',
                'sebastian/object-enumerator',
                'sebastian/object-reflector',
                'sebastian/recursion-context',
                'sebastian/resource-operations',
                'sebastian/type',
                'sebastian/version',
                'symfony/config',
                'symfony/console',
                'symfony/deprecation-contracts',
                'symfony/dom-crawler',
                'symfony/dotenv',
                'symfony/event-dispatcher',
                'symfony/event-dispatcher-contracts',
                'symfony/filesystem',
                'symfony/finder',
                'symfony/options-resolver',
                'symfony/polyfill-ctype',
                'symfony/polyfill-intl-grapheme',
                'symfony/polyfill-intl-normalizer',
                'symfony/polyfill-mbstring',
                'symfony/polyfill-php72',
                'symfony/polyfill-php80',
                'symfony/polyfill-php81',
                'symfony/process',
                'symfony/service-contracts',
                'symfony/stopwatch',
                'symfony/string',
                'symfony/var-dumper',
                'symfony/yaml',
                'theseer/tokenizer',
                'twig/twig',
                'willdurand/negotiation',
            ],
            $vendor
                ->map(static fn($package) => $package->name()->toString())
                ->sort(static fn($a, $b) => $a <=> $b)
                ->toList(),
        );
    }
}
